
ORIGINAL_COMMENT_MARKER = '#'
NEW_COMMENT_MARKER = '#'
ANF_BUFFER_VAR_NAME = '%_'
PROV_INFO_MARKER = '--'
PROV_INFO_EXT_CHAR = ';'
PROV_INFO_SPLIT_CHAR = '|'
BLOCK_IDENTIFIER = 'L'
SSA_BUFFER_VAR_NAME = '_SSA_'